//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCR2WebApp.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public System.Guid ID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyID { get; set; }
    }
}
