USE [master]
GO

/****** Object:  Database [SupplyMe]    Script Date: 08/05/2014 21:50:04 ******/
CREATE DATABASE [SupplyMe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SupplyMe', FILENAME = N'C:\SQLData\SupplyMe.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'SupplyMe_log', FILENAME = N'C:\SQLData\SupplyMe_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO

ALTER DATABASE [SupplyMe] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SupplyMe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SupplyMe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SupplyMe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SupplyMe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SupplyMe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SupplyMe] SET ARITHABORT OFF 
GO

ALTER DATABASE [SupplyMe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SupplyMe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SupplyMe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SupplyMe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SupplyMe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SupplyMe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SupplyMe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SupplyMe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SupplyMe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SupplyMe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SupplyMe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SupplyMe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SupplyMe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SupplyMe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SupplyMe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SupplyMe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SupplyMe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SupplyMe] SET RECOVERY FULL 
GO

ALTER DATABASE [SupplyMe] SET  MULTI_USER 
GO

ALTER DATABASE [SupplyMe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SupplyMe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SupplyMe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SupplyMe] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SupplyMe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SupplyMe] SET  READ_WRITE 
GO


